#!/usr/bin/env bash
set -euo pipefail

CAL_ROOT="${CAL_ROOT:-/home/kms/LLaVA_calibration}"
DISCOVERY_ROOT="${DISCOVERY_ROOT:-$CAL_ROOT/experiments/pope_discovery/tau_c_calibration_mix_train2014_2785}"

VGA_ROOT="${VGA_ROOT:-/home/kms/VGA_origin}"
MODEL_PATH="${MODEL_PATH:-liuhaotian/llava-v1.5-7b}"
IMAGE_FOLDER="${IMAGE_FOLDER:-/home/kms/data/images/mscoco/images/train2014}"
QUESTION_FILE="${QUESTION_FILE:-$DISCOVERY_ROOT/discovery_q_with_object.jsonl}"
TAXONOMY_CSV="${TAXONOMY_CSV:-$DISCOVERY_ROOT/per_case_compare.csv}"
HEADSET_JSON="${HEADSET_JSON:-$CAL_ROOT/experiments/pope_discovery/discovery_headset.json}"
OUT_DIR="${OUT_DIR:-$DISCOVERY_ROOT/vga_cost_aware_gain_router_artifact}"

CONV_MODE="${CONV_MODE:-llava_v1}"
DEVICE="${DEVICE:-cuda}"
TEMPERATURE="${TEMPERATURE:-0}"
TOP_P="${TOP_P:-1.0}"
SAMPLING="${SAMPLING:-false}"
MAX_GEN_LEN="${MAX_GEN_LEN:-8}"
NUM_BEAMS="${NUM_BEAMS:-1}"

CD_ALPHA="${CD_ALPHA:-0.02}"
ATTN_COEF="${ATTN_COEF:-0.2}"
START_LAYER="${START_LAYER:-16}"
END_LAYER="${END_LAYER:-24}"
HEAD_BALANCING="${HEAD_BALANCING:-simg}"
ATTN_NORM="${ATTN_NORM:-false}"
LATE_START="${LATE_START:-16}"
LATE_END="${LATE_END:-24}"
PROBE_FEATURE_MODE="${PROBE_FEATURE_MODE:-static_headset}"
PROBE_POSITION_MODE="${PROBE_POSITION_MODE:-baseline_yesno_preview}"
PROBE_BRANCH_SOURCE="${PROBE_BRANCH_SOURCE:-preview}"
PROBE_FORCE_MANUAL_FULLSEQ="${PROBE_FORCE_MANUAL_FULLSEQ:-false}"
PROBE_PREVIEW_MAX_NEW_TOKENS="${PROBE_PREVIEW_MAX_NEW_TOKENS:-3}"
PROBE_PREVIEW_REUSE_BASELINE="${PROBE_PREVIEW_REUSE_BASELINE:-true}"
PROBE_PREVIEW_FALLBACK_TO_PROMPT_LAST="${PROBE_PREVIEW_FALLBACK_TO_PROMPT_LAST:-true}"

TAU="${TAU:--0.0068411549792573}"
FEATURE_VARIANT="${FEATURE_VARIANT:-no_abs}"
DEPLOYMENT_BUDGET="${DEPLOYMENT_BUDGET:-0.30}"
SEED="${SEED:-42}"
MAX_SAMPLES="${MAX_SAMPLES:--1}"

mkdir -p "$OUT_DIR"
cd "$CAL_ROOT"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" \
CAL_ROOT="$CAL_ROOT" \
VGA_ROOT="$VGA_ROOT" \
MODEL_PATH="$MODEL_PATH" \
IMAGE_FOLDER="$IMAGE_FOLDER" \
QUESTION_FILE="$QUESTION_FILE" \
TAXONOMY_CSV="$TAXONOMY_CSV" \
HEADSET_JSON="$HEADSET_JSON" \
OUT_DIR="$OUT_DIR" \
CONV_MODE="$CONV_MODE" \
DEVICE="$DEVICE" \
TEMPERATURE="$TEMPERATURE" \
TOP_P="$TOP_P" \
SAMPLING="$SAMPLING" \
MAX_GEN_LEN="$MAX_GEN_LEN" \
NUM_BEAMS="$NUM_BEAMS" \
CD_ALPHA="$CD_ALPHA" \
ATTN_COEF="$ATTN_COEF" \
START_LAYER="$START_LAYER" \
END_LAYER="$END_LAYER" \
HEAD_BALANCING="$HEAD_BALANCING" \
ATTN_NORM="$ATTN_NORM" \
LATE_START="$LATE_START" \
LATE_END="$LATE_END" \
PROBE_FEATURE_MODE="$PROBE_FEATURE_MODE" \
PROBE_POSITION_MODE="$PROBE_POSITION_MODE" \
PROBE_BRANCH_SOURCE="$PROBE_BRANCH_SOURCE" \
PROBE_FORCE_MANUAL_FULLSEQ="$PROBE_FORCE_MANUAL_FULLSEQ" \
PROBE_PREVIEW_MAX_NEW_TOKENS="$PROBE_PREVIEW_MAX_NEW_TOKENS" \
PROBE_PREVIEW_REUSE_BASELINE="$PROBE_PREVIEW_REUSE_BASELINE" \
PROBE_PREVIEW_FALLBACK_TO_PROMPT_LAST="$PROBE_PREVIEW_FALLBACK_TO_PROMPT_LAST" \
TAU="$TAU" \
FEATURE_VARIANT="$FEATURE_VARIANT" \
DEPLOYMENT_BUDGET="$DEPLOYMENT_BUDGET" \
SEED="$SEED" \
MAX_SAMPLES="$MAX_SAMPLES" \
bash "$CAL_ROOT/scripts/build_vga_cost_aware_gain_router_artifact_9000.sh"

echo "[done] $OUT_DIR"
echo "[saved] $OUT_DIR/router/summary.json"
